// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {backend} from '../models';

export function AddTask(arg1:string,arg2:time.Time,arg3:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetTasks():Promise<Array<backend.Task>>;

export function MarkTaskCompleted(arg1:number):Promise<void>;

export function UndoTaskCompletion(arg1:number):Promise<void>;
