// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3) {
  return window['go']['backend']['App']['AddTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['backend']['App']['DeleteTask'](arg1);
}

export function GetTasks() {
  return window['go']['backend']['App']['GetTasks']();
}

export function MarkTaskCompleted(arg1) {
  return window['go']['backend']['App']['MarkTaskCompleted'](arg1);
}

export function UndoTaskCompletion(arg1) {
  return window['go']['backend']['App']['UndoTaskCompletion'](arg1);
}
